### ISSUE TITLE
boot_shutdown_tools must be specified as a tag, but it is not.

### ISSUE THREAD

**Issue by Yukio247** [tier4/AutowareSignage#47]
@yabuta @ta661 cc: @0x126 

beta/v2.0.0のreposでboot_shutdown_toolsのブランチ指定がハッシュ固定になっていました。
このハッシュ値からだいぶ更新かかっていて、これが原因で、サイネージのshutdownができなくなっています。
https://github.com/tier4/AutowareSignage/blob/beta/v2.0.0/signage.repos#L21
ここは、`v0.1.0`に指定する必要があるように思います。車外音声も同様です。

加えて、beta.reposも作成されていますが、[signage.repos](https://github.com/tier4/AutowareSignage/blob/beta/v2.0.0/signage.repos)と整合が取れていないように思うのですが、ここはどのような運用にしているのですか？github actionsは使用していないですか？

**Comment by tkhmy** [comment]
fixed in https://github.com/tier4/AutowareSignage/pull/48
